services:
  backend_redis:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-us-east-1}.amazonaws.com/yefp1/backend-redis:${BACKEND_REDIS_TAG:-latest}
    restart: unless-stopped
    user: appuser
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    read_only: true
    tmpfs:
      - /tmp
    # env_file:
    #   - .backend.env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DEBUG=${DEBUG}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "9000:9000"
    networks:
       - app
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/test_connection/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
    app:
