services:
  backend_redis:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-us-east-1}.amazonaws.com/yefp1/backend-redis:${BACKEND_REDIS_TAG:-latest}
    restart: unless-stopped
    user: appuser
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    read_only: true
    tmpfs:
      - /tmp
    # env_file:
    #   - .backend.env
    environment:
      - CORS_ALLOWED_ORIGINS=${CACHE_CORS_ALLOWED_ORIGINS}
      - DEBUG=${CACHE_DEBUG}
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SSL_ENABLED=True
    secrets:
      - redis_password
      - secret_key
    ports:
      - "9000:9000"
    networks:
       - app
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/test_connection/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

secrets:
  redis_password:
    file: /home/ubuntu/backend_redis/redis_password
  secret_key:
    file: /home/ubuntu/backend_redis/django_secret_key

networks:
    app:
